import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { corsHeaders } from '../_shared/cors.ts'

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY')
const GOOGLE_API_KEY = Deno.env.get('GOOGLE_API_KEY')
const GOOGLE_SEARCH_ENGINE_ID = Deno.env.get('GOOGLE_CSE_ID')

interface ProductSuggestion {
  name: string
  description: string
  searchQuery: string
}

interface ProductWithImage {
  name: string
  description: string
  imageUrl?: string
  thumbnailUrl?: string
}

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { query } = await req.json()

    if (!query || typeof query !== 'string') {
      return new Response(
        JSON.stringify({ error: 'Query parameter is required' }),
        { 
          status: 400, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      )
    }

    if (!GEMINI_API_KEY) {
      return new Response(
        JSON.stringify({ error: 'Gemini API key not configured' }),
        { 
          status: 500, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      )
    }

    // Step 1: Use Gemini to generate product suggestions
    const productSuggestions = await generateProductSuggestions(query)
    
    // Step 2: For each suggestion, search for images
    const productsWithImages = await Promise.all(
      productSuggestions.map(async (product) => {
        const imageUrl = await searchForProductImage(product.searchQuery)
        return {
          name: product.name,
          description: product.description,
          imageUrl: imageUrl?.url,
          thumbnailUrl: imageUrl?.thumbnailUrl
        }
      })
    )

    return new Response(
      JSON.stringify({ 
        products: productsWithImages,
        query: query
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )

  } catch (error) {
    console.error('Search wishlist products function error:', error)
    return new Response(
      JSON.stringify({ 
        error: 'Internal server error',
        message: error.message 
      }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )
  }
})

async function generateProductSuggestions(query: string): Promise<ProductSuggestion[]> {
  const prompt = `You are a tabletop gaming expert. Based on this user query: "${query}", suggest 3-5 specific tabletop gaming products that match their request. 

Focus on:
- Miniatures and models (Warhammer 40k, Age of Sigmar, etc.)
- Board games
- RPG books and accessories
- Paint sets and hobby supplies
- Terrain and scenery
- Dice and gaming accessories

For each product, provide:
1. Exact product name (be specific with edition/version if applicable)
2. Brief description (1-2 sentences about what it is)
3. Search query for finding images (specific product name)

Format as JSON array:
[
  {
    "name": "Exact Product Name",
    "description": "Brief description of the product",
    "searchQuery": "specific search terms for images"
  }
]

Only return the JSON array, no other text.`

  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 1000,
        }
      })
    })

    if (!response.ok) {
      throw new Error(`Gemini API error: ${response.status}`)
    }

    const data = await response.json()
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!generatedText) {
      throw new Error('No content generated by Gemini')
    }

    // Parse the JSON response
    const suggestions = JSON.parse(generatedText)
    return suggestions.slice(0, 5) // Limit to 5 suggestions

  } catch (error) {
    console.error('Error generating product suggestions:', error)
    // Fallback: return generic suggestions based on query
    return generateFallbackSuggestions(query)
  }
}

function generateFallbackSuggestions(query: string): ProductSuggestion[] {
  const lowerQuery = query.toLowerCase()
  
  if (lowerQuery.includes('warhammer') || lowerQuery.includes('40k')) {
    return [
      {
        name: "Warhammer 40,000 Space Marines Combat Patrol",
        description: "A starter set for Space Marines including models, rules, and dice",
        searchQuery: "Warhammer 40k Space Marines Combat Patrol box"
      },
      {
        name: "Citadel Paint Set",
        description: "Essential paint set for miniature painting",
        searchQuery: "Citadel paint set Warhammer"
      }
    ]
  }
  
  if (lowerQuery.includes('dnd') || lowerQuery.includes('d&d') || lowerQuery.includes('dungeon')) {
    return [
      {
        name: "D&D Player's Handbook",
        description: "Core rulebook for Dungeons & Dragons 5th edition",
        searchQuery: "D&D Player's Handbook 5e"
      },
      {
        name: "D&D Dice Set",
        description: "Polyhedral dice set for tabletop RPGs",
        searchQuery: "D&D dice set polyhedral"
      }
    ]
  }
  
  // Generic tabletop gaming suggestions
  return [
    {
      name: "Tabletop Gaming Dice Set",
      description: "Essential polyhedral dice for RPGs and board games",
      searchQuery: "tabletop gaming dice set"
    },
    {
      name: "Miniature Paint Brushes",
      description: "High-quality brushes for miniature painting",
      searchQuery: "miniature painting brushes"
    }
  ]
}

async function searchForProductImage(searchQuery: string): Promise<{url: string, thumbnailUrl: string} | null> {
  if (!GOOGLE_API_KEY || !GOOGLE_SEARCH_ENGINE_ID) {
    return null
  }

  try {
    const searchParams = new URLSearchParams({
      key: GOOGLE_API_KEY,
      cx: GOOGLE_SEARCH_ENGINE_ID,
      q: searchQuery,
      searchType: 'image',
      num: '1',
      safe: 'active',
      imgSize: 'large',
      imgType: 'photo'
    })

    const apiUrl = `https://www.googleapis.com/customsearch/v1?${searchParams}`
    const response = await fetch(apiUrl)
    
    if (!response.ok) {
      return null
    }

    const data = await response.json()
    const image = data.items?.[0]
    
    if (image) {
      return {
        url: image.link,
        thumbnailUrl: image.image?.thumbnailLink || image.link
      }
    }
    
    return null
  } catch (error) {
    console.error('Error searching for product image:', error)
    return null
  }
}
