/*
  # Redesign wishlist table for AI-powered product search

  1. Changes
    - Drop existing wishlist table and recreate with new schema
    - Add product_name, description, and image_url columns
    - Maintain existing RLS policies for user data security
    - Preserve user_uid and created_at columns

  2. New Schema
    - id: Primary key
    - user_uid: Foreign key to auth.users
    - product_name: Name of the product (replaces item_name)
    - description: AI-generated product description
    - image_url: URL of product image
    - created_at: Timestamp
*/

-- Drop existing wishlist table and recreate with new schema
DROP TABLE IF EXISTS public.wishlist CASCADE;

-- Create new wishlist table with AI-powered product fields
CREATE TABLE public.wishlist (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_uid text REFERENCES auth.users(id) ON DELETE CASCADE,
    product_name text NOT NULL,
    description text,
    image_url text
);

-- Enable RLS
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Users can view their own wishlist items
CREATE POLICY "Users can view their own wishlist items" ON public.wishlist
    FOR SELECT USING (auth.uid() = user_uid::uuid);

-- Users can insert their own wishlist items
CREATE POLICY "Users can insert their own wishlist items" ON public.wishlist
    FOR INSERT WITH CHECK (auth.uid() = user_uid::uuid);

-- Users can update their own wishlist items
CREATE POLICY "Users can update their own wishlist items" ON public.wishlist
    FOR UPDATE USING (auth.uid() = user_uid::uuid)
    WITH CHECK (auth.uid() = user_uid::uuid);

-- Users can delete their own wishlist items
CREATE POLICY "Users can delete their own wishlist items" ON public.wishlist
    FOR DELETE USING (auth.uid() = user_uid::uuid);

-- Admins can manage all wishlist items (for moderation purposes)
CREATE POLICY "Admins can manage all wishlist items" ON public.wishlist
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE users.id = auth.uid()::text 
            AND users.is_admin = true
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE users.id = auth.uid()::text 
            AND users.is_admin = true
        )
    );

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS wishlist_user_uid_idx ON public.wishlist(user_uid);
CREATE INDEX IF NOT EXISTS wishlist_created_at_idx ON public.wishlist(created_at);

-- Add comments
COMMENT ON TABLE public.wishlist IS 'User wishlist items for AI-powered product search and tracking';
COMMENT ON COLUMN public.wishlist.product_name IS 'Name of the product the user wants to purchase';
COMMENT ON COLUMN public.wishlist.description IS 'AI-generated description of the product';
COMMENT ON COLUMN public.wishlist.image_url IS 'URL of an image representing the product';
COMMENT ON COLUMN public.wishlist.user_uid IS 'ID of the user who owns this wishlist item';
