/*
  # Create wishlist table with RLS policies

  1. Changes
    - Create `wishlist` table if it doesn't exist
    - Add proper RLS policies for user access control
    - Users can only manage their own wishlist items

  2. Security
    - Enable RLS on wishlist table
    - Users can view, insert, update, and delete only their own wishlist items
    - Admin users have full access to all wishlist items for moderation
*/

-- Create wishlist table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.wishlist (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    item_name text,
    user_uid text REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view their own wishlist items" ON public.wishlist;
DROP POLICY IF EXISTS "Users can insert their own wishlist items" ON public.wishlist;
DROP POLICY IF EXISTS "Users can update their own wishlist items" ON public.wishlist;
DROP POLICY IF EXISTS "Users can delete their own wishlist items" ON public.wishlist;
DROP POLICY IF EXISTS "Admins can manage all wishlist items" ON public.wishlist;

-- Create RLS policies
-- Users can view their own wishlist items
CREATE POLICY "Users can view their own wishlist items" ON public.wishlist
    FOR SELECT USING (auth.uid() = user_uid::uuid);

-- Users can insert their own wishlist items
CREATE POLICY "Users can insert their own wishlist items" ON public.wishlist
    FOR INSERT WITH CHECK (auth.uid() = user_uid::uuid);

-- Users can update their own wishlist items
CREATE POLICY "Users can update their own wishlist items" ON public.wishlist
    FOR UPDATE USING (auth.uid() = user_uid::uuid)
    WITH CHECK (auth.uid() = user_uid::uuid);

-- Users can delete their own wishlist items
CREATE POLICY "Users can delete their own wishlist items" ON public.wishlist
    FOR DELETE USING (auth.uid() = user_uid::uuid);

-- Admins can manage all wishlist items (for moderation purposes)
CREATE POLICY "Admins can manage all wishlist items" ON public.wishlist
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE users.id = auth.uid()::text 
            AND users.is_admin = true
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.users 
            WHERE users.id = auth.uid()::text 
            AND users.is_admin = true
        )
    );

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS wishlist_user_uid_idx ON public.wishlist(user_uid);
CREATE INDEX IF NOT EXISTS wishlist_created_at_idx ON public.wishlist(created_at);

-- Add comments
COMMENT ON TABLE public.wishlist IS 'User wishlist items for tracking desired purchases';
COMMENT ON COLUMN public.wishlist.item_name IS 'Name of the item the user wants to purchase';
COMMENT ON COLUMN public.wishlist.user_uid IS 'ID of the user who owns this wishlist item';